# Generated by Django 4.2.4 on 2023-09-01 05:29

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_hide_email_useraccount_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile_background',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.get_profile_background_filepath),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='profile_song',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.get_profile_song_filepath),
        ),
    ]
